# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "A:/Program Files/CMake/bin/cmake.exe"

# The command to remove a file.
RM = "A:/Program Files/CMake/bin/cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = E:/STXETX_Protocol

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = E:/STXETX_Protocol

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"A:/Program Files/CMake/bin/cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"A:/Program Files/CMake/bin/cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start E:/STXETX_Protocol/CMakeFiles E:/STXETX_Protocol//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start E:/STXETX_Protocol/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named stxetx_protocol

# Build rule for target.
stxetx_protocol: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stxetx_protocol
.PHONY : stxetx_protocol

# fast build rule for target.
stxetx_protocol/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stxetx_protocol.dir/build.make CMakeFiles/stxetx_protocol.dir/build
.PHONY : stxetx_protocol/fast

src/main.obj: src/main.c.obj
.PHONY : src/main.obj

# target to build an object file
src/main.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stxetx_protocol.dir/build.make CMakeFiles/stxetx_protocol.dir/src/main.c.obj
.PHONY : src/main.c.obj

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stxetx_protocol.dir/build.make CMakeFiles/stxetx_protocol.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stxetx_protocol.dir/build.make CMakeFiles/stxetx_protocol.dir/src/main.c.s
.PHONY : src/main.c.s

src/stxetx_protocol.obj: src/stxetx_protocol.c.obj
.PHONY : src/stxetx_protocol.obj

# target to build an object file
src/stxetx_protocol.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stxetx_protocol.dir/build.make CMakeFiles/stxetx_protocol.dir/src/stxetx_protocol.c.obj
.PHONY : src/stxetx_protocol.c.obj

src/stxetx_protocol.i: src/stxetx_protocol.c.i
.PHONY : src/stxetx_protocol.i

# target to preprocess a source file
src/stxetx_protocol.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stxetx_protocol.dir/build.make CMakeFiles/stxetx_protocol.dir/src/stxetx_protocol.c.i
.PHONY : src/stxetx_protocol.c.i

src/stxetx_protocol.s: src/stxetx_protocol.c.s
.PHONY : src/stxetx_protocol.s

# target to generate assembly for a file
src/stxetx_protocol.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stxetx_protocol.dir/build.make CMakeFiles/stxetx_protocol.dir/src/stxetx_protocol.c.s
.PHONY : src/stxetx_protocol.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... stxetx_protocol"
	@echo "... src/main.obj"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/stxetx_protocol.obj"
	@echo "... src/stxetx_protocol.i"
	@echo "... src/stxetx_protocol.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

